#######################
#=MESSAGE=OVER=HEADER=#
#######################

version: 1.4 #DONT TOUCH!

debug: false #debug mode.

settings: #plugin settings
  1_20_experimental: false #enable experimental possibilities from 1.20
  messages:
    command:
      enable: "bubble enabled"
      disable: "bubble disabled"
      send: "bubble send"
      create: "bubble create"
#The priority of a bubble model is determined by its position in the config. The higher, the more priority the model.
models:
  test-model-bubble: #Some message configuration
    #channels are used only to adjust the visibility of the message to certain players
    channel: "local" #the channel to which the BubbleArmorStand Model belongs. By default, "all". All channels start with the sign "#". Supports custom channels from plugins to chat channels ("#global", "#local", "#custom-channel")
    settings:
      format: '&7{message}'
  test-private-model:
    channel: "private" #When the "private" channel is specified (without #), the bubble of this model will be visible to players who communicate in private messages using the /tell or /msg command (custom private messages implemented by other plugins are supported)
    settings:
      format: '&7{message}'
      #There are no other fields specified in this config, so the other fields have a default value.
  test-more-channel-model:
    channel: ["#all", "#private", "#command", "custom_channel"] #You can specify multiple channels. private - showing bubble model for private messages. command - showing bubble model for bubble called with the command.
  test-all-model: #defaul
    channel: "#all" #When it is "all", then this model will be available for all channels
    permission: "moh.global-message"
    particle:
      enable: true
      type: CLOUD # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
      count: 4 #count of particle
      offset-x: 0.2 #the maximum random offset on the X axis
      offset-y: 0.2 #the maximum random offset on the X axis
      offset-z: 0.2 #the maximum random offset on the Z axis
    sound:
      enable: true
      type: BLOCK_ANVIL_STEP # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
      volume: 3 #The volume of the sound
      pitch: 3 #The pitch of the sound
    settings:
      format: '%player_name% {message}' #Default format. Supports PlaceholderAPI and HEX colors (example: &#123456)
      #format: #Group format!
        #The priority is determined by the position of the format. The higher the priority.
        #premium:
          #permission: 'moh.global-message.premium'
          #format: '&ePREMIUM &b&l%message%'
        #vip:
          #permission: 'moh.global-message.vip'
          #format: '&cVIP &e%message%'
        #default:
          #format: '%message%' #default format. format haven't permission
      distance: 10
      bias-y: 2.15 #height spawn of bubbles. The value is calculated experimentally.
      visible-text-for-owner: true
      lifetime: #Automatic lifetime bubbles settings
        time-per-char: 0.7 #Time per one character
        min-time: 2 #Minimum lifetime
        max-time: 20 #Maximum lifetime
      max-size-line: 24 #Maximum size of one bubble